@startuml
left to right direction
skinparam backgroundColor #FFFFFF
skinparam usecaseBorderColor #111111
skinparam actorBorderColor #111111
skinparam shadowing false

actor Player as P

rectangle Game {
  usecase "Start game" as UC_Start
  usecase "Create new blocks" as UC_Create
  usecase "Edit keys" as UC_Edit
  usecase "End game" as UC_End
}

P --> UC_Start
P --> UC_Create
P --> UC_Edit
P --> UC_End

@enduml
